/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistacontrolador;

/**
 *
 * @author DAM2_03
 */
public class Ventana_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton_radio_op1 = new javax.swing.JRadioButton();
        Boton_radio_op3 = new javax.swing.JRadioButton();
        Boton_radio_op2 = new javax.swing.JRadioButton();
        Boton_check_op4 = new javax.swing.JCheckBox();
        Boton_check_op5 = new javax.swing.JCheckBox();
        Boton_check_op6 = new javax.swing.JCheckBox();
        Caja_Texto = new javax.swing.JTextField();
        Combobox_items = new javax.swing.JComboBox<>();
        Spinner_1 = new javax.swing.JSpinner();
        Texto_Correo = new javax.swing.JLabel();
        Caja_correo = new javax.swing.JTextField();
        Barra_deslizante = new javax.swing.JSlider();
        Boton_pulsar = new javax.swing.JToggleButton();
        Boton_radio_op1_espejo = new javax.swing.JRadioButton();
        Boton_radio_op2_espejo = new javax.swing.JRadioButton();
        Boton_radio_op3_espejo = new javax.swing.JRadioButton();
        Boton_check_op4_espejo = new javax.swing.JCheckBox();
        Boton_check_op5_espejo = new javax.swing.JCheckBox();
        Boton_check_op6_espejo = new javax.swing.JCheckBox();
        Caja_texto_espejo = new javax.swing.JTextField();
        Barra_deslizante_espejo = new javax.swing.JSlider();
        Spinner_espejo = new javax.swing.JSpinner();
        Combobox_items_espejo = new javax.swing.JComboBox<>();
        Caja_correo_espejo = new javax.swing.JTextField();
        Texto_Correo_espejo = new javax.swing.JLabel();
        Boton_pulsar_espejo = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Boton_radio_op1.setText("Opcion 1");
        Boton_radio_op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_radio_op1ActionPerformed(evt);
            }
        });

        Boton_radio_op3.setText("Opcion 3");
        Boton_radio_op3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_radio_op3ActionPerformed(evt);
            }
        });

        Boton_radio_op2.setText("Opcion 2");
        Boton_radio_op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_radio_op2ActionPerformed(evt);
            }
        });

        Boton_check_op4.setText("Opcion 4");
        Boton_check_op4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_check_op4ActionPerformed(evt);
            }
        });

        Boton_check_op5.setText("Opcion 5");
        Boton_check_op5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_check_op5ActionPerformed(evt);
            }
        });

        Boton_check_op6.setText("Opcion 6");
        Boton_check_op6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_check_op6ActionPerformed(evt);
            }
        });

        Caja_Texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caja_TextoActionPerformed(evt);
            }
        });

        Combobox_items.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Combobox_items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combobox_itemsActionPerformed(evt);
            }
        });

        Texto_Correo.setText("Correo");

        Boton_pulsar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paul\\Documents\\GitHub\\pr-ctica-2-4-elementos-interfaz-mixta-PaulCarvajal\\SOL\\practica2-4\\src\\vistacontrolador\\b_off.png")); // NOI18N
        Boton_pulsar.setSelected(true);
        Boton_pulsar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Boton_pulsarItemStateChanged(evt);
            }
        });

        Boton_radio_op1_espejo.setText("Opcion 1");
        Boton_radio_op1_espejo.setEnabled(false);

        Boton_radio_op2_espejo.setText("Opcion 2");
        Boton_radio_op2_espejo.setEnabled(false);

        Boton_radio_op3_espejo.setText("Opcion 3");
        Boton_radio_op3_espejo.setEnabled(false);

        Boton_check_op4_espejo.setText("Opcion 4");
        Boton_check_op4_espejo.setEnabled(false);

        Boton_check_op5_espejo.setText("Opcion 5");
        Boton_check_op5_espejo.setEnabled(false);

        Boton_check_op6_espejo.setText("Opcion 6");
        Boton_check_op6_espejo.setEnabled(false);

        Caja_texto_espejo.setEnabled(false);

        Spinner_espejo.setEnabled(false);

        Combobox_items_espejo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Combobox_items_espejo.setEnabled(false);

        Texto_Correo_espejo.setText("Correo");

        Boton_pulsar_espejo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paul\\Documents\\GitHub\\pr-ctica-2-4-elementos-interfaz-mixta-PaulCarvajal\\SOL\\practica2-4\\src\\vistacontrolador\\b_off.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Boton_radio_op1)
                                        .addGap(37, 37, 37)
                                        .addComponent(Boton_check_op4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Boton_radio_op2)
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Boton_check_op6)
                                            .addComponent(Boton_check_op5))))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Spinner_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Caja_Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Boton_radio_op1_espejo)
                                    .addComponent(Boton_radio_op2_espejo)
                                    .addComponent(Boton_radio_op3_espejo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(Texto_Correo_espejo)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Boton_check_op4_espejo)
                                            .addComponent(Boton_check_op5_espejo)
                                            .addComponent(Boton_check_op6_espejo))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Spinner_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Caja_texto_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Combobox_items_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(Caja_correo_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Boton_radio_op3)
                                .addGap(142, 142, 142)
                                .addComponent(Combobox_items, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Texto_Correo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Caja_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Barra_deslizante_espejo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Barra_deslizante, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Boton_pulsar)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Boton_pulsar_espejo)
                        .addGap(62, 62, 62))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_radio_op1)
                    .addComponent(Boton_check_op4)
                    .addComponent(Caja_Texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Barra_deslizante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton_check_op5)
                            .addComponent(Spinner_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_radio_op2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton_check_op6)
                            .addComponent(Combobox_items, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_radio_op3))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Caja_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Texto_Correo)))
                    .addComponent(Boton_pulsar))
                .addGap(57, 57, 57)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton_radio_op1_espejo)
                            .addComponent(Boton_check_op4_espejo)
                            .addComponent(Caja_texto_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Barra_deslizante_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton_radio_op2_espejo)
                            .addComponent(Boton_check_op5_espejo)
                            .addComponent(Spinner_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton_radio_op3_espejo)
                            .addComponent(Boton_check_op6_espejo)
                            .addComponent(Combobox_items_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Boton_pulsar_espejo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caja_correo_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Texto_Correo_espejo))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_check_op4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_check_op4ActionPerformed
       Boton_check_op4_espejo.setSelected(Boton_check_op4.isSelected());
    }//GEN-LAST:event_Boton_check_op4ActionPerformed

    private void Boton_check_op5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_check_op5ActionPerformed
        Boton_check_op5_espejo.setSelected(Boton_check_op5.isSelected());
    }//GEN-LAST:event_Boton_check_op5ActionPerformed

    private void Boton_check_op6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_check_op6ActionPerformed
        Boton_check_op6_espejo.setSelected(Boton_check_op6.isSelected());
    }//GEN-LAST:event_Boton_check_op6ActionPerformed

    private void Boton_pulsarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Boton_pulsarItemStateChanged
       
    }//GEN-LAST:event_Boton_pulsarItemStateChanged

    private void Boton_radio_op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_radio_op1ActionPerformed
        Boton_radio_op1_espejo.setSelected(Boton_radio_op1.isSelected());
    }//GEN-LAST:event_Boton_radio_op1ActionPerformed

    private void Boton_radio_op2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_radio_op2ActionPerformed
       Boton_radio_op2_espejo.setSelected(Boton_radio_op2.isSelected());
    }//GEN-LAST:event_Boton_radio_op2ActionPerformed

    private void Boton_radio_op3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_radio_op3ActionPerformed
         Boton_radio_op3_espejo.setSelected(Boton_radio_op3.isSelected());
    }//GEN-LAST:event_Boton_radio_op3ActionPerformed

    private void Caja_TextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caja_TextoActionPerformed
        Caja_texto_espejo.setText(Caja_Texto.getText());
    }//GEN-LAST:event_Caja_TextoActionPerformed

    private void Combobox_itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combobox_itemsActionPerformed
        Combobox_items_espejo.setSelectedItem(Combobox_items.getSelectedItem());
    }//GEN-LAST:event_Combobox_itemsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider Barra_deslizante;
    private javax.swing.JSlider Barra_deslizante_espejo;
    private javax.swing.JCheckBox Boton_check_op4;
    private javax.swing.JCheckBox Boton_check_op4_espejo;
    private javax.swing.JCheckBox Boton_check_op5;
    private javax.swing.JCheckBox Boton_check_op5_espejo;
    private javax.swing.JCheckBox Boton_check_op6;
    private javax.swing.JCheckBox Boton_check_op6_espejo;
    private javax.swing.JToggleButton Boton_pulsar;
    private javax.swing.JToggleButton Boton_pulsar_espejo;
    private javax.swing.JRadioButton Boton_radio_op1;
    private javax.swing.JRadioButton Boton_radio_op1_espejo;
    private javax.swing.JRadioButton Boton_radio_op2;
    private javax.swing.JRadioButton Boton_radio_op2_espejo;
    private javax.swing.JRadioButton Boton_radio_op3;
    private javax.swing.JRadioButton Boton_radio_op3_espejo;
    private javax.swing.JTextField Caja_Texto;
    private javax.swing.JTextField Caja_correo;
    private javax.swing.JTextField Caja_correo_espejo;
    private javax.swing.JTextField Caja_texto_espejo;
    private javax.swing.JComboBox<String> Combobox_items;
    private javax.swing.JComboBox<String> Combobox_items_espejo;
    private javax.swing.JSpinner Spinner_1;
    private javax.swing.JSpinner Spinner_espejo;
    private javax.swing.JLabel Texto_Correo;
    private javax.swing.JLabel Texto_Correo_espejo;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
